service: murmur-lambda

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: ap-northeast-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**
   - ./google_client_credentials.json

functions:
  murmur-lambda:
    handler: bin/murmur-lambda
    events:
      - schedule: 'cron(0/15 0-14,22-23 * * ? *)'
